### ISSUE TITLE
Warp appears to use cuda:0 despite cuda:1 being set as default

### ISSUE THREAD

**Issue by wuwuyiyirong5** [NVIDIA/warp#101]
Cuda 0 device is used for display(performance low). Cuda:1 device is specified for warp(performance high).
The cuda 1 device is setted for warp, use wp.set_device("cuda:1").But when the project run, both cuda 0
and cuda 1 work, and the procedure time is the same as
slow device cuda 0.

**Comment by shi-eric** [comment]
Hi @wuwuyiyirong5, is this still an issue? Do you have a minimal example that illustrates the problem?

**Comment by shi-eric** [comment]
> “CUDA_VISIBLE_DEVICE” variable can be used to assign the cuda device， this works.

Thanks for the update. If you have an example of the original issue, we can still take a look at it to try to understand if there's a bug in Warp when it comes to device selection.
