### ISSUE TITLE
Support AOT deployment

### ISSUE THREAD

**Issue by yangfengzzz** [NVIDIA/warp#102]
In production pipeline, when I train a AI model to deploy on my device, I also need physics sumulation work with it. AOT deployment will be better way to use this framework into production.

**Comment by mmacklin** [comment]
Hi @yangfengzzz , can you elaborate on what you would need for AOT deployment?

Is the problem compiling kernels after deployment? It is possible to collect the kernel cache (see location printed at `wp.init()`), and then distribute those with your app.

You would just need to manually update the `warp.config.kernel_cache_dir` to read them from your desired location.

Let me know if you need something else.

**Comment by mmacklin** [comment]
It is possible to include the `warp.dll` inside engines like Unity/Unreal - there is a native interface to this lib.:

https://github.com/NVIDIA/warp/blob/main/warp/native/warp.h

You can use this to load the pre-compiled kernels, access mesh functions, etc.
