### ISSUE TITLE
will Warp be able to cover all the features of the C++ CUDA API?

### ISSUE THREAD

**Issue by Guptajakala** [NVIDIA/warp#11]
I'm a fresh learner for CUDA and was getting familiar with C++ CUDA API. This repo looks interesting! I'm wondering will it later support all the C++ CUDA API completely, by using only python to implement any kind of CUDA kernels?

**Comment by mmacklin** [comment]
Hi @Guptajakala,

Warp's goal is to make it easier to write GPU kernels from Python, not expose all of CUDA. Doing things like managing shared memory, warp-level intrinsics, etc are out of the scope of Warp and I think better done through C++.

For this you could modify the builtin.h and builtin.py to register your own functions. Eventually we will expose this capability with an API so you can also register external C++ headers directly from your Python Warp modules.

Cheers,
Miles
