### ISSUE TITLE
render_points does not accept wp.array

### ISSUE THREAD

**Issue by jc211** [NVIDIA/warp#111]
In the function ``render_points`` in OpenGLRenderer: ``np.array(points)`` does not work when ``points = state.particle_q``. In other words when points is a ``wp.array``.  This error is raised: 

``RuntimeError("Item indexing is not supported on wp.array objects")``

**Comment by eric-heiden** [comment]
Hi @jc211,

Thank you for reporting this issue! We will have a fix for this in the next release.
