### ISSUE TITLE
Omniverse USD Composer Mandelbrot example flickering

### ISSUE THREAD

**Issue by johndoe888** [NVIDIA/warp#116]
The Mandelbrot example shows some disturbing flickering when going full-screen and hovering around (and sometimes just so).

I think the dynamic textures to be supercool for displaying high-res calculated Warp results, but with the flickering very difficult to work with and show the results to others.

Environment:
AWS EC2 g5.4xlarge connected via RemoteDesktop
USD Composer 2023.1
Warp 0.82 (the standard that came with the installation of USD Composer 2023.1)

**Comment by christophercrouzet** [comment]
Hi @johndoe888, thanks for sharing this issue!

The flickering that you mentioned was also reported on our end alongside the other issue that you ran into with #93. The corresponding team has assigned a high priority on it it so we're expecting it to be addressed in an upcoming release of the Composer app.

In the meantime, one thing that we observed is that reducing the scene FPS _seems_ to help with the flickering. In our case, 60 FPS seemed to behave more or less as expected.

Thank you for your patience!

**Comment by johndoe888** [comment]
For me 24 FPS did the trick. 60 FPS still flickered in fullscreen mode. Maybe it is different across RemoteDesktop.

**Comment by shi-eric** [comment]
@christophercrouzet Is this fixed now?

**Comment by christophercrouzet** [comment]
Yes, it should have been addressed in more recent releases of USD Composer!
