### ISSUE TITLE
memcpy easier to access

### ISSUE THREAD

**Issue by jc211** [NVIDIA/warp#118]
Is it possible to make the memcpy functions easier to access in python? I can see they are part of the runtime but it would nice if they were accessible via wp.memcpy_h2d

**Comment by mmacklin** [comment]
Hi @jc211, can I ask the use case? Is `wp.copy()` on arrays not enough here?

I am a bit wary of exposing all these 'low level' operations on the main API. But I think accessing them through the context object is OK if you really need them.
