### ISSUE TITLE
OpenGLRenderer: render_points goes through the cpu even when updating

### ISSUE THREAD

**Issue by jc211** [NVIDIA/warp#128]
Updating the positions of points participating in a pbd simulation would benefit from render_points having not to go back to the cpu on every iteration if the positions and radii are already on the gpu. I think the use of a wp.glRegisteredGLBuffer might be good here.

**Comment by eric-heiden** [comment]
Hi @jc211,

If the number of points and the name of the points instance hasn't changed between calls to `render_points`, there won't be any CPU conversions/copy operations. The sphere instances are directly updated from the `points` array if it is a Warp array using the `wp.RegisteredGLBuffer` for the instance transforms in the ShapeInstancer: https://github.com/NVIDIA/warp/blob/main/warp/render/render_opengl.py#L2557-L2564

Best,
Eric
