### ISSUE TITLE
How can I get bvh identifier and use relevent kernel?

### ISSUE THREAD

**Issue by ZiXuanVickyLu** [NVIDIA/warp#130]
In the document, I found a kernel called warp.bvh_query_aabb(), and the first parameter is a bvh identifier. But I do not find there is a 'bvh' type (which should exist a builder, I guess?) where I can refer it with a identifier. In the document, it indicates that bvh is associated with a Mesh, I guess?
So how can I use this kernel? Or where can I get the bvh identifier?
(I sincerely ask for a simple example :-)
![image](https://github.com/NVIDIA/warp/assets/53465084/cca40da1-4a00-44f8-9c4d-e8f51d8c5805)

**Comment by mmacklin** [comment]
Hi @ZiXuanVickyLu, please find an example of using the Bvh class here: https://github.com/NVIDIA/warp/blob/main/warp/tests/test_bvh.py#L81.

We will work on better documentation for this feature as well.

Cheers,
Miles

**Comment by ZiXuanVickyLu** [comment]
Appreciate!
