### ISSUE TITLE
Clamp particle velocity to a vmax that assures system stability

### ISSUE THREAD

**Issue by NRHuntoon** [NVIDIA/warp#131]
Semi-Implicit integrators benefit from having maximum velocities to ensure stability. Numerical stability of `SemiImplicitIntegegrator` would be enhanced if a maximum velocity was passed into the kernel and any particle velocity that exceeded this was clamped.

Passing either a global vmax based on the minimum mesh dimensions, or a per particle vmax array would be ideal.

**Comment by mmacklin** [comment]
Thanks @NRHuntoon, as discussed on Discord this makes sense to me - @eric-heiden could you take a look at implementing this?

**Comment by eric-heiden** [comment]
@NRHuntoon we will have an option for a global maximum on particle velocity in the next release which will clamp the velocity magnitude.

**Comment by shi-eric** [comment]
`Model.particle_max_velocity` added in 1.0.0-beta.1.
