### ISSUE TITLE
usd renderer using lowercase

### ISSUE THREAD

**Issue by cadop** [NVIDIA/warp#143]
I think it would be good to change:

https://github.com/NVIDIA/warp/blob/1535cdecc626c9f527b99467ed94dbf8a20cc00a/warp/render/render_usd.py#L75

to

         self.up_axis = up_axis.upper()

and use capitals here:

https://github.com/NVIDIA/warp/blob/1535cdecc626c9f527b99467ed94dbf8a20cc00a/warp/render/render_usd.py#L100

USD doesn't like lowercase, and this caused an issue for awhile when I was trying to render with warp. For example, this modification to the sphere fails

```
        if not instancer:
            if colors is None:
                instancer = UsdGeom.PointInstancer.Define(self.stage, instancer_path)
                
                # Create a capsule instead of a sphere
                instancer_capsule = UsdGeom.Capsule.Define(self.stage, instancer.GetPath().AppendChild("capsule"))
                instancer_capsule.GetAxisAttr().Set(self.up_axis)
                
```

because `GetAxisAttr()` expects capital, but warp expects lowercase.

**Comment by mmacklin** [comment]
Ah, thanks @cadop - sounds like a good change. @eric-heiden .

**Comment by eric-heiden** [comment]
@cadop Thanks for reporting this, the `up_axis` parameter will be in upper case in the next release.
