### ISSUE TITLE
make the non-commercial clause more visible in the readme

### ISSUE THREAD

**Issue by pieper** [NVIDIA/warp#15]
This looks like an interesting library, but after reviewing the license I realized it says it's for non-commercial use only.  I think that information should be made more clear so people don't invest time unless they are comfortable with that limitation.  (Of course an even better solution would be to change the license to something like Apache 2, in case you are open to that option.)

**Comment by mmacklin** [comment]
Hi @pieper, thanks for feedback - I've added a section in the README.md to point people to the license. We are evaluating more permissive licenses for future versions.

Cheers,
Miles

**Comment by pieper** [comment]
Thanks for the edit @mmacklin.  Just for clarity I suggest some extra wording if you don't mind.

https://github.com/NVIDIA/warp/pull/17

**Comment by mmacklin** [comment]
Hi @pieper, apologies for the delay - I added the suggested note to the README.md.

Thanks,
Miles
