### ISSUE TITLE
Adding cubic root

### ISSUE THREAD

**Issue by Dolorousrtur** [NVIDIA/warp#150]
Hey, thanks to the developers for this incredible library!

In my project, I need to precisely compute the cubic roots of double-precision variables. But it seems that warp does not have it implemented (`warp.pow(x, 1/3)` is not precise enough).

I reckon it shouldn't be too difficult to add it since it only needs to call `cbrt` function in CUDA. I tried to find a way to add cbrt to the source code of Warp same as it is done with `sqrt`, but couldn't do that yet.

Could you direct me to how (in which files) the `sqrt` support is implemented, s.t. I can add `cbrt` the same way?

Many thanks in advance!

**Comment by daedalus5** [comment]
Hi @Dolorousrtur, thanks for your request. `cbrt` will be in the next Warp release.

**Comment by Dolorousrtur** [comment]
Hi, @daedalus5 ! That's great!

In the meantime, could you please describe the steps I can follow to add it to the code myself s.t. I can build the updated version from sources? If it won't take too much time for you.

Thank you in advance!

**Comment by shi-eric** [comment]
`cbrt` was included in the `v1.0.0-beta.5` release: https://github.com/NVIDIA/warp/releases
