### ISSUE TITLE
Self-collision in cloth simulation

### ISSUE THREAD

**Issue by kkaracam** [NVIDIA/warp#152]
Hello,

I have been experimenting with some simple cloth simulations. I wish to enable self-collision during a simulation but cannot seem to find any information related to the subject. So I wanted to ask:

1. Does Warp support self-collision for cloth?
2. If so, how can I enable/disable it?

**Comment by christophercrouzet** [comment]
Hi @kkaracam, the solvers shipped with Warp currently don't implement self-collision for cloth, apologies. This feature will likely make its way in the future but this is not a priority at the moment. Some have rolled their own solvers in Warp to implement the features they needed, so maybe that's something you could experiment with if you'd like to?

**Comment by kkaracam** [comment]
Hi @christophercrouzet, thank you for your response. I'll consider my options accordingly.
