### ISSUE TITLE
update the mesh during simulation 

### ISSUE THREAD

**Issue by cyanzhao42** [NVIDIA/warp#160]
Hi, thanks for the great work. I am interested in simulating cloth with moving objects. I am following the example code: https://github.com/NVIDIA/warp/blob/main/examples/example_sim_cloth.py here. I am wondering if it would be possible to update the "mesh"  (builder.add_shape_mesh) vertices during the simulation.

I found the example here - https://github.com/NVIDIA/warp/blob/main/examples/example_mesh.py, on how to update the mesh, however, the mesh object is not compatible with wp.sim. I am wondering if there is a smart way to address this. Thanks!

**Comment by mmacklin** [comment]
Hi @cyanzhao42, yes take a look at the `wp.sim.Mesh` class: https://github.com/NVIDIA/warp/blob/main/warp/sim/model.py#L256. Here you can see it contains a regular mesh that can be updated + refit() as desired.

Cheers,
Miles

**Comment by mmacklin** [comment]
The Omniverse cloth node extension also does this, you can look here for an example:

https://github.com/NVIDIA/warp/blob/main/exts/omni.warp/omni/warp/nodes/_impl/OgnClothSimulate.py#L368

Cheers,
Miles

**Comment by SangHunHan92** [comment]
Thanks for great work !

I want to simulate a cloth for a moving object, exactly like this question.
But I couldn't find updated + refit() in the link below:
https://github.com/NVIDIA/warp/blob/main/warp/sim/model.py#L256

Has the function to update vertices been moved? So how is it available now?

**Comment by SangHunHan92** [comment]
https://github.com/NVIDIA/warp/blob/bfbd0258479ea1378788c2ff5bdbbdc1da385612/warp/types.py#L2997-L3004
https://github.com/NVIDIA/warp/blob/bfbd0258479ea1378788c2ff5bdbbdc1da385612/warp/examples/core/example_mesh.py#L116-L129

Is this what you were referring to?
