### ISSUE TITLE
Adjoint of Matmul

### ISSUE THREAD

**Issue by moradza** [NVIDIA/warp#168]
The current matmul and batched_matmul implementations break the gradient flow, as an example, in line https://github.com/NVIDIA/warp/blob/79a56a9c2754bbec1418e490efafd43091056856/warp/types.py#L3177 
one should change `a.ptr` with `ctypes.c_void_p(adj_a.ptr)` and beta should set to 1. In the current implementation, old gradient of `a` is overwritten by matmul call, similar issue holds for `b`, `c`, and `d`.

**Comment by mmacklin** [comment]
Hi @moradza, thanks for the report - @daedalus5 can you take a look?

**Comment by c0d1f1ed** [comment]
Fixed by https://github.com/NVIDIA/warp/commit/9ae387756329f4cc20b528bd65bc6d7d5478176c
