### ISSUE TITLE
Boids example not loading

### ISSUE THREAD

**Issue by cadop** [NVIDIA/warp#170]
I just installed 2022.2.2. Clicked on the Examples, press play, nothing happens. 

![image](https://github.com/NVIDIA/warp/assets/11399119/6828f7f2-e70f-4e15-b874-9c8d26b8e234)

I think the example is just the action graph and is missing the scene setup (e.g. `2023-12-21 00:07:51  [Warning] [omni.graph.core.plugin] Could not find node type interface for 'omni.graph.action_nodes.OnLoaded'`

To clarify, I am not using the omnigraph node, I am just clicking on the example file 
![image](https://github.com/NVIDIA/warp/assets/11399119/ad814992-a79a-475c-8f29-19166d000146)

**Comment by cadop** [comment]
When adding a Tick in the graph, it asks for an updated warp 

![image](https://github.com/NVIDIA/warp/assets/11399119/bbe60701-0a01-499c-a75b-4e4f5e7edc94)

after that, it asks to updated usdrt 
![image](https://github.com/NVIDIA/warp/assets/11399119/07c20fb6-6b12-4750-b52e-ceae71e6ddb8)

But there doesnt seem to be that option in 2023.2.2 beta

**Comment by christophercrouzet** [comment]
Hi @cadop , this specific sample indeed requires a version of Composer USD that isn't released yet, so it won't run on current versions. We need to make this clearer somehow. Apologies for the inconvenience caused!

**Comment by cadop** [comment]
I guess it shouldn't have been included in the release?  Can the release of warp get updated to remove the example? It's not possible to run it all, so kinda weird.

**Comment by shi-eric** [comment]
@christophercrouzet Is this fixed now?

**Comment by christophercrouzet** [comment]
It should work with Kit 106.0, which has just been released, but USD Composer hasn't been updated yet.

**Comment by cadop** [comment]
I can open the usda file directly in IsaacSim 4.0 and it works. 

A note though; the link on the graph object is broken. 

<img width="348" alt="image" src="https://github.com/NVIDIA/warp/assets/11399119/e4914453-5a5f-490c-aba6-d33c06dc16f3">

Goes to: https://docs.omniverse.nvidia.com/extensions/latest/ext_omnigraph/node-library/nodes/omni-warp/warpsampleprimflocking-1.html

**Comment by christophercrouzet** [comment]
Thanks @cadop! This seems to be the case for other nodes as well (not only Warp ones), I'll report this to the corresponding team.
