### ISSUE TITLE
Docs missing debugging link

### ISSUE THREAD

**Issue by cadop** [NVIDIA/warp#178]
The hyperlink for the python example file here https://nvidia.github.io/warp/debugging.html#step-through-debugging

goes to a file not found: https://github.com/NVIDIA/warp/blob/main/warp/tests/walkthrough_debug.py

**Comment by shi-eric** [comment]
Thanks for catching this! I'll fix the typo in the name of the test.

**Comment by c0d1f1ed** [comment]
Fixed in [v0.13.0](https://github.com/NVIDIA/warp/releases/tag/v0.13.0). Thanks Eric!
