### ISSUE TITLE
Is there OpenMP support in the prebuilt Clang & LLVM libraries from packman?

### ISSUE THREAD

**Issue by AnthCol** [NVIDIA/warp#181]
Hello, 
I am trying to modify the code generation in Warp to support OpenMP. The primary goal is to speed up execution of warp kernels on the CPU by parallelizing the loops in the generated code that call "length_cpu_kernel_forward" and "length_cpu_kernel_backward".
I am wondering if the prebuilt Clang & LLVM libraries within packman are compatible with that idea?
I am aware that there is an option to clone and build LLVM from scratch, and I could possibly enable OpenMP support through the CMake defines in build_llvm.py - Just wondering if there is a way to do this through the prebuilt libraries from packman. Among other things, I have tried adding the OpenMP flag (-fopenmp) to the arguments within cpp_to_llvm (in clang.cpp) which later gets used by clang::CompilerInvocation::CreateFromArgs(). The command is recognized by the compiler, but there are missing symbols, all of which begin with ___kmpc, and are related to OpenMP directives/pragmas.
The error looks like this:
`JIT session error: Symbols not found: [ ___kmpc_critical, ___kmpc_end_critical, ___kmpc_for_static_fini, ___kmpc_for_static_init_8u, ___kmpc_fork_call ]`
From what I can tell, these appear to be linker errors, which is why I am wondering whether the included LLVM & Clang binaries support OpenMP. Last year colleagues of mine were able to get OpenMP working on Warp version 0.7.2 (which uses the system compiler) using the -fopenmp flag, and I am working on porting our prototype to the latest, Clang & LLVM based version of Warp.

Thank you in advance, 
Anthony

**Comment by c0d1f1ed** [comment]
Hi Anthony, thanks for the inquiry. It's very interesting to hear that your team got GCC's `-fopenmp` support working for Warp.

The prebuilt Clang and LLVM libraries on packman currently use release version 15.0.7, while OpenMP support has only recently been merged into the LLVM main branch and will be part of the upcoming version 18 release.

So I'm afraid the only potential way to get it working would be to build a more recent version of LLVM from source by using the `--build_llvm` flag when building Warp, and modifying `build_from_source_for_arch()` to check out a recent revision.

**Comment by c0d1f1ed** [comment]
@AnthCol we're now looking into this ourselves to see if OpenMP use is a good way to accelerate the CPU path.

Indeed linking the `___kmpc_*` symbols is necessary to have the JIT-compiled kernels communicate with the OpenMP runtime. Note that symbol linking happens in `wp_load_obj()`.

Could you share any notes you and/or your colleagues made so we can align the approach?

**Comment by AnthCol** [comment]
When I was working on this change I did end up having to use the `--build_llvm` flag as you previously mentioned, but I didn't ever change the LLVM version. Instead, I modified the build flags (`cmake_gen`) array in `build_from_source_for_arch` and then did the linking to the built-out library in the `load_obj` function (now `wp_load_obj` as you mentioned). <br>
The libomp library (for my computers architecture) was found here: `warp/external/llvm-project/out/install/release-x86_64/lib/libomp.so`


```c++
/* In load_obj function after the following:
auto dll = jit->createJITDylib(module_name); 

if (!dll)
{
    std::cerr << “Failed to create JITDylib: “ << toString(dll.takeError()) << std::endl;
    return -1;
}
*/

auto handle = jit->getExecutionSession().getExecutorProcessControl().loadDylib(omp_lib_path);

if (handle) 
{
    dll->addGenerator(std::make_unique<llvm::orc::EPCDynamicLibrarySearchGenerator>(jit->getExecutionSession(), *handle));
} 
else 
{
    std::cerr << "Unable to load OpenMP dynamic library.\n";
    return -1;
}
```

#### OpenMP:
The only OpenMP directives I added to the generated code were:
- `pragma omp parallel for`
- `pragma omp critical` (above instances where `= wp::atomic_` was found)

#### Issues:
The above OpenMP directives were not enough to have perfect results during regression testing. By the time I finished working on the project (4 months during my undergrad) I had three failing testcases that I had not yet resolved:

- `/warp/tests/test_fem.py`
- `/warp/tests/test_mlp.py`
- `/warp/tests/test_grad.py`


#### Results:

Results were good, but unfortunately the timing tests I ran were made by me and are in a codebase I no longer have access to. The results below are real, but the descriptions of the testing code are coming from my memory.


All values are an average over three attempts:

- Simple 1D kernel test (this kernel had a single loop inside of it up to some hardcoded value). 
    - 1 thread -> 113.73s
    - 8 threads -> 17.74s
    - 16 threads -> 12.36s
- Image Processing (3D kernel, 15000 x 15000 px img - this was some relatively simple operation on the image, not involving any atomic operations)
    - 1 thread -> 13.96s
    - 8 threads -> 4.70s
    - 16 threads -> 2.97s

These tests were ran on an AMD Ryzen 7 PRO 6850U (8 cores, 16 logical processors, 2.7 GHz base, 4.7 GHz boost). I do not have any results for how much longer the code generation and JIT compilation processes became as a result of my changes.

<hr>

Thanks for reaching out and if you have any other questions regarding my work on the project please let me know.<br>


*Please note:* All of my work was done on version 1.0.2 of Warp

**Comment by shi-eric** [comment]
Thank you for providing all those details, @AnthCol!

**Comment by AnthCol** [comment]
You're welcome :)
