### ISSUE TITLE
Alternative tetmesh format

### ISSUE THREAD

**Issue by honglin-c** [NVIDIA/warp#198]
Would it be possible to provide an example where the user reads a tetmesh from a .mesh file? Thank you! :)

**Comment by honglin-c** [comment]
I was using the following code (with libigl python binding) to load the tetmesh, which was unsuccessful so far. 

```
  V, T, F = igl.read_mesh("./data/tetmesh/spot.mesh")

  V = Vt.Vec3fArray.FromNumpy(V)
  T = Vt.IntArray.FromNumpy(T)

  builder.add_soft_mesh(
      pos=wp.vec3(0.0, 2.0, 0.0),
      rot=wp.quat_identity(),
      scale=0.1,
      vel=wp.vec3(0.0, 0.0, 0.0),
      vertices=V, 
      indices=T, 
      density=100.0, 
      k_mu=2000.0, 
      k_lambda=2000.0, 
      k_damp=2.0,
      tri_ke=0.0,
      tri_ka=1e4,
      tri_kd=0.0,
      tri_drag=0.0,
      tri_lift=0.0,
  )
```
![image](https://github.com/NVIDIA/warp/assets/24607222/b2483932-4599-4d6d-aa99-286e6c8a365f)

**Comment by mmacklin** [comment]
Hi @honglin-c, could you provide the .mesh file for this example so we can reproduce?

Thanks,
Miles

**Comment by samuelpmish** [comment]
I'm guessing it's this mesh: https://github.com/honglin-c/INSR-PDE/blob/main/elasticity/data/spot.mesh

download link: [spot.zip](https://github.com/NVIDIA/warp/files/14920701/spot.zip)

I tried writing a minimal reproducer with @honglin-c 's approach

```py
import os
import math

import warp as wp
import warp.examples
import warp.sim
import warp.optim
import warp.sim.render

import igl
import scipy as sp
import numpy as np
from pxr import Usd, UsdGeom, Vt

wp.init()

# sim model
builder = wp.sim.ModelBuilder()

V, T, F = igl.read_mesh("/path/to/meshes/spot.mesh")

V = Vt.Vec3fArray.FromNumpy(V)
T = Vt.IntArray.FromNumpy(T)

builder.add_soft_mesh(
    pos=wp.vec3(0.0, 0.0, 0.0),
    rot=wp.quat_identity(),
    scale=2.0,
    vel=wp.vec3(0.0, 0.0, 0.0),
    vertices=V,
    indices=T,
    density=1.0,
    k_mu=2000.0,
    k_lambda=2000.0,
    k_damp=2.0,
    tri_ke=0.0,
    tri_ka=1e-8,
    tri_kd=0.0,
    tri_drag=0.0,
    tri_lift=0.0,
)

# finalize model
model = builder.finalize(requires_grad=False)

model.soft_contact_ke = 2.0e3
model.soft_contact_kd = 0.1
model.soft_contact_kf = 10.0
model.soft_contact_mu = 0.7

model.ground = True

state = model.state(requires_grad=False)

# rendering
renderer = wp.sim.render.SimRenderer(model, "spot.usd")

renderer.begin_frame(0)
renderer.render(state)
renderer.end_frame()

renderer.save()
```

and it seemed to work:
![Screenshot from 2024-04-09 08-24-03](https://github.com/NVIDIA/warp/assets/16393433/abe0f414-fa4f-42ea-8f1e-4285fd05a8f2)

But I'm very new to using warp, so I might be doing something wrong!

**Comment by mmacklin** [comment]
Nice! Thank you @samuelpmish! @honglin-c does this solve your problem?

**Comment by honglin-c** [comment]
Wowww thank you so much @samuelpmish!! :)))

**Comment by honglin-c** [comment]
Actually, I realized the problem was with the simulation and the scale of the tetmesh. 
For instance, I will have this problem for the code below. But if I change `scale=5.0` to `scale=10.0` in `builder.add_soft_mesh`, the simulation will run without problem. Still trying to figure out what's going wrong here...

**Comment by honglin-c** [comment]
This is with `scale = 5.0`:

<img width="471" alt="image" src="https://github.com/NVIDIA/warp/assets/24607222/f521d3c3-243a-44b1-9100-8de7238b6bbc">

Without the simulation (I commented out `example.step()`) , the rendering looks fine: 
<img width="471" alt="image" src="https://github.com/NVIDIA/warp/assets/24607222/7b0f036b-18f8-4d4a-8c88-8ef69d560184">

**Comment by honglin-c** [comment]
But if I simply change `scale=5.0` to `scale=10.0` in `builder.add_soft_mesh()`, the simulation just runs perfectly! :0 
I'm having a mesh colliding with the ground and then bouncing back in the code: 
<img width="473" alt="image" src="https://github.com/NVIDIA/warp/assets/24607222/da3838d2-05ae-401c-a89e-3205f1317a98">
<img width="473" alt="image" src="https://github.com/NVIDIA/warp/assets/24607222/61bd9a0f-ce00-4719-872d-1303b8e14a41">
<img width="473" alt="image" src="https://github.com/NVIDIA/warp/assets/24607222/84e2a950-80a2-4c81-af92-b30e223838b5">

**Comment by mmacklin** [comment]
This is probably just a classic example of simulation stability being dependent on the scale, e.g.: by scaling everything down then everything gets lighter while stiffness is staying the same, i.e.: the problem got a lot stiffer, which means you need smaller time-steps to be stable.

If you are reducing scale you generally need to reduce the time-step size (dt) or take more substeps as well.

Cheers,
Miles

**Comment by honglin-c** [comment]
Thank you so much for the explanations! Now I finally understand. :)

**Comment by shi-eric** [comment]
Resolved by @samuelpmish
