### ISSUE TITLE
Graph Capture with PyTorch

### ISSUE THREAD

**Issue by jc211** [NVIDIA/warp#217]
Can I capture torch code from within warp's graph capture? For example, is it possible for this code to work?

```python
a = torch.ones(10).cuda()
with wp.ScopedCapture() as c:
         a.mul_(10)
wp.capture_launch(c.graph)
```

**Comment by eric-heiden** [comment]
Hi @jc211,

Yes, it is possible to capture torch and Warp code on the same CUDA graph by making sure that all operations happen on the same CUDA stream. 

Please take a look at these test functions where we show how to run Warp code on a torch-created CUDA stream and vice-versa to capture CUDA graphs:

https://github.com/NVIDIA/warp/blob/main/warp/tests/test_torch.py#L512
https://github.com/NVIDIA/warp/blob/main/warp/tests/test_torch.py#L554
