### ISSUE TITLE
Recommended way to debug a kernel

### ISSUE THREAD

**Issue by HimangiM** [NVIDIA/warp#232]
Thank you for providing such a great framework for simulation projects!

I have a warp kernel in my code and one of the warp tensors has nan values. I am unable to debug which tensor has nan values. It seems like wp.printf only works for scalar values and wp.isnan requires a wp.func wrapper in the kernel. I am curious to know what is the recommended way to debug a kernel in this situation? Additionally, are there any ways for kernel debugging recommended by the warp community?

Thanks,
Himangi

**Comment by shi-eric** [comment]
Hi Himangi, have you tried running your program with `wp.config.verify_fp = True`? ([Docs](https://nvidia.github.io/warp/configuration.html#basic-global-settings)) That should hopefully help you narrow it down to a specific kernel and maybe which array is getting bad values.

The `wp.isnan()` issue sounds unintentional, but it was just added so maybe there is something we overlooked. You should be able to use it directly in the kernels without wrapping it in a `@wp.func`. Can you provide an example showing what's not working with `wp.isnan()`?

Finally if it's possible to debug your code by running Warp kernels on the CPU, the instructions in our docs here might be helpful: https://nvidia.github.io/warp/debugging.html#step-through-debugging
