### ISSUE TITLE
Contact force measurement 

### ISSUE THREAD

**Issue by IntrovertInDisguise** [NVIDIA/warp#246]
### Description

I need to print out the contact forces and the direction of the same during each contact using the contact sensor(akin to what is available on IsaacSim).
### Context

I am trying to verify my contact model with differentiable physics contact models
```[tasklist]
### Tasks
```

**Comment by eric-heiden** [comment]
Hi @IntrovertInDisguise,

You could modify the [`eval_rigid_contacts` kernel](https://github.com/NVIDIA/warp/blob/main/warp/sim/integrator_euler.py#L849) which accumulates the contact wrenches (linear and angular forces) for each rigid body given the contact point information (which includes the contact normal in world space). In your case you could compute the contact wrench for each contact point individually and store it to another Warp array that contains the contact sensor forces, optionally only the contacts you are interested in (e.g. based on the indix of the two colliding shapes, `contact_shape0` and `contact_shape1`) could be filtered.
