### ISSUE TITLE
Extra ray query functions for multiple intersections and no direction

### ISSUE THREAD

**Issue by shi-eric** [NVIDIA/warp#253]
### Discussed in https://github.com/NVIDIA/warp/discussions/212

<div type='discussions-op-text'>

<sup>Originally posted by **cadop** April 30, 2024</sup>
Please let me know if there is already a simple/fast way to do this. 

It would be helpful if there were some extra ray query functions, similar in spirit to the point query. 

The bvh query lets me iterate over the intersections. It would be helpful if there was a mesh ray that would do the same thing.  I also have a need for the closest point on the mesh along an axis, so a ray in both directions from a start point would be very helpful. 

https://nvidia.github.io/warp/modules/functions.html#warp.mesh_query_ray</div>

**Comment by Irene-123** [comment]
Hi @shi-eric 
I went through this issue and looking to contribute here
I was hoping if this is an priority task and I could take it up as my good-first-issue?
Lmk if there's something else I can work upon, thanks!
