### ISSUE TITLE
[QUESTION] Cannot import 'omni'

### ISSUE THREAD

**Issue by biansy000** [NVIDIA/warp#261]
I want to write a clothes simulation program following ``exts/omni.warp/omni/warp/nodes/_impl/OgnClothSimulate.py``. However, I cannot import omni in the code.
```
ModuleNotFoundError: No module named 'omni'
```

**Comment by christophercrouzet** [comment]
Hi @biansy000, are you running `import omni` from within an Omniverse application? The `exts` folder is dedicated to extensions for the Omniverse platform, so it won't run in a standalone Python environment. You can check [`warp/examples/sim/example_cloth.py`](https://github.com/NVIDIA/warp/blob/69c5b8b72719f86d855d389630d1a746951a1240/warp/examples/sim/example_cloth.py) for the latter.
