### ISSUE TITLE
Can't run Warp in NVIDIA graphics mode on Pop!_OS

### ISSUE THREAD

**Issue by fajar7xx** [NVIDIA/warp#270]
### Bug Description

when I set my pop os using Nvidia graphics, I can't show but if I set in hybrid graphics I can run. I didn't know how to set up this or is this bug?

### System Information

pop os 22.04 LTS based on ubuntu 22.o4
acer aspire gaming 7
intel core i5 12450H
nvidia rtx 2050
32GB Ram

**Comment by shi-eric** [comment]
Hi @fajar7xx, we have no experience with this distribution. Could you please provide some error messages that illustrate what you're seeing? For example, can you provide:

- Output of `nvidia-smi`
- Output of `wp.init()` after `import warp as wp` for the two cases (NVIDIA graphics, hybrid graphics) you mentioned?
