### ISSUE TITLE
[QUESTION] <Load usd from url>

### ISSUE THREAD

**Issue by Spphire** [NVIDIA/warp#274]
Error in 'pxrInternal_v0_24__pxrReserved__::UsdStage::Open' at line 1059 in file /opt/USD/pxr/usd/usd/stage.cpp : 'Failed to open layer @http:/omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.0/Isaac/Robots/ShadowHand/shadow_hand_instanceable.usd@'

Is it possible to load usd from url?

**Comment by christophercrouzet** [comment]
Hi @Spphire, is this a question specific to OpenUSD rather than Warp? I managed to open this reference using [Omniverse](https://docs.omniverse.nvidia.com), so give that a try maybe.
