### ISSUE TITLE
Can't find warp in omniverse kit

### ISSUE THREAD

**Issue by lyd405121** [NVIDIA/warp#28]
- I clone this repository and build it
- Run some example and get some usd files
![usd-cloth](https://user-images.githubusercontent.com/16344694/169805006-457410d3-fc04-4c35-9728-7db40acdf1d9.png)
- But I can't reproduce the whole simulation but the fisrt frame
- So I guess maybe I should install warp extesion in omniverse kit
![no_werp](https://user-images.githubusercontent.com/16344694/169805233-c219f338-2604-4b27-88bd-068c0a5c3dc5.png)

- Unfortunately， I can't find it
- The version for omniverse kit is 103.1.1 the latest

**Comment by lyd405121** [comment]
- I clone this resposry and build it
- Run some example and get some usd files
![usd-cloth](https://user-images.githubusercontent.com/16344694/169805006-457410d3-fc04-4c35-9728-7db40acdf1d9.png)
- But I can not let reproduce the whole simulation but the fisrt frame
- So I guess maybe I should install warp extesion in omniverse kit
![no_werp](https://user-images.githubusercontent.com/16344694/169805233-c219f338-2604-4b27-88bd-068c0a5c3dc5.png)

- Unfortunately， I can't find it
- The version for omniverse kit is 103.1.1 the latest

**Comment by lyd405121** [comment]
- How silly I am!
- In animation layer, I found it

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/16344694/169806807-b6ae8c6b-7590-40e7-92b3-0b38a9f80770.gif)

- But I still can not find warp extesion in omniverse kit
- Am I making another mistake?

**Comment by cadop** [comment]
You need to add the warp directory to kit mini extensions. 
Check the section Push it to Git, it has an image showing what it looks like to add the directory. 
http://omniverse-docs-production.s3-website-us-west-1.amazonaws.com/kit-sdk/103.0/docs/guide/get_started_extensions.html

btw, this is better for a discussion question than an issue.

**Comment by lyd405121** [comment]
> u need to add the warp directory to kit mini extensions

Thanks! I am on my way to explore warp
