### ISSUE TITLE
[QUESTION] Is it possible to pass gradient through wp.sim.collide function?

### ISSUE THREAD

**Issue by Spphire** [NVIDIA/warp#280]
Imaging a scene with Cube A stack upon Cube B (with collide)
From Cube A and target position, we can get l2 loss,
and I want to get gradient on Cube B's body_q after backward that loss, is it possible?

As my attempt, it's 0.0 on Cube B's body_q but not on Cube A's body_q (it's for sure),
but what i meant is that Cube B definitely can affect Cube A's position, with collide simulation.

**Comment by eric-heiden** [comment]
Hi @Spphire,

Yes, the collision handling is differentiable. See the example [`test_box_pushing_on_rails` in test_sim_grad.py](https://github.com/NVIDIA/warp/blob/main/warp/tests/test_sim_grad.py) where two boxes are pushed against each other and gradients are propagated.
