### ISSUE TITLE
[REQUEST] Add atomic_max and atomic_min for float64

### ISSUE THREAD

**Issue by swan2818** [NVIDIA/warp#284]
### Description
For now, the atomic_max and atomic_min operators in Warp are for float and int only.

### Context
Please support float64 for the atomic_max and atomic_min operators.

**Comment by Irene-123** [comment]
Hi @swan2818 @shi-eric 
I went through this issue and looking to contribute here

**Comment by shi-eric** [comment]
Hi @Irene-123, thanks for volunteering! I think @daedalus5 might already be working on this issue. The other two you expressed an interest in should be open for you to take up.

**Comment by Irene-123** [comment]
That's great, thank you @shi-eric 
Is there a discord channel to have a discussion?

**Comment by shi-eric** [comment]
> That's great, thank you @shi-eric Is there a discord channel to have a discussion?

Yes, there is a channel for Warp in the Omniverse Discord server ([link](https://discord.com/invite/nvidiaomniverse))

**Comment by daedalus5** [comment]
Yes I have an MR in for this now.
