### ISSUE TITLE
Example crashed

### ISSUE THREAD

**Issue by lyd405121** [NVIDIA/warp#31]
I am really intestrest in the cloth simulation， So I want to run the "example_sim_humanoid.py"
But, Get an error:

![error](https://user-images.githubusercontent.com/16344694/172280852-2b259016-04e4-4d0f-85fb-537a988194f2.png)

Some example works well:

![11](https://user-images.githubusercontent.com/16344694/172280883-7d9ccbba-be11-4a63-b481-3ecc3dab055c.gif)

I guess the human was represented by the union of capsule sdf and some works from

[airMesh](http://mmacklin.com/airMeshesPreprint.pdf) & [sdfconact](https://mmacklin.com/sdfcontact.pdf)

![10](https://user-images.githubusercontent.com/16344694/172281190-e0a6df26-6f0a-4b78-a370-516505040630.png)

**Comment by mmacklin** [comment]
The error code you have is due to the fact that there is no CUDA device present (it needs a CUDA GPU for graph capture).

We improved error handling for this in the examples now.
