### ISSUE TITLE
[BUG] OpenGLRenderer example: example_render_opengl.py

### ISSUE THREAD

**Issue by mmmovania** [NVIDIA/warp#312]
### Bug Description

When setting the argument --num_tiles to 1 as default, the code gives a divison by zero error at 
`line 117 aspect_ratio = example.renderer.tile_height / example.renderer.tile_width`
![Image](https://github.com/user-attachments/assets/dc7698df-ba54-41b1-8b92-9b48350035fd)

An easy fix is to simply change line 34 in class Example from this
        if num_tiles > 1:
to this
        if num_tiles >= 1:

and then it works fine.

**Comment by shi-eric** [comment]
Thanks for reporting the issue, it should now be fixed in the `main` branch.
