### ISSUE TITLE
AttributeError: module 'warp' has no attribute 'sub'

### ISSUE THREAD

**Issue by PAMinerva** [NVIDIA/warp#33]
Hi, I'm trying to execute this sample

https://github.com/matthias-research/pages/blob/master/tenMinutePhysics/16-GPUCloth.py

However, I wasn't able to run it properly. In particular, I get the following message.

```
  File "c:\Users\Alex\Desktop\16-GPUCloth.py", line 875, in <module>
    z = wp.sub(x, y)
AttributeError: module 'warp' has no attribute 'sub'
```

**Comment by mmacklin** [comment]
I think Matthias has published it before the newer version of Warp was released :)

I just pushed latest changes, so please try again.

Cheers,
Miles

**Comment by PAMinerva** [comment]
It works! Thank you!
