### ISSUE TITLE
[REQUEST] Allow raising errors from kernels

### ISSUE THREAD

**Issue by nvlukasz** [NVIDIA/warp#336]
### Description
Currently, there is no way to raise an error from a Warp kernel.  Adding a `wp.assert()` builtin would work.  To reduce perf overhead, consider enabling it only in debug mode.

### Context
Request from @mehdiataei

**Comment by shi-eric** [comment]
This should hopefully be addressed by 7933bbb57d3ca7609e6498e54291b1838de86de4
