### ISSUE TITLE
[BUG] nvjitlink required for warp

### ISSUE THREAD

**Issue by louhz** [NVIDIA/warp#338]
Looks like nvjitlink is required by warp, which supported by cudatoolkit 12 i remember and maybe need to rewrite the requirement in readme

**Comment by shi-eric** [comment]
Hey @louhz, we plan to fix this issue by only requiring nvjitlink when building Warp with MathDX support. This was an oversight when adding the new changes.

**Comment by shi-eric** [comment]
The issue should be fixed in `main` now. Please reopen this issue if you have any more problems with this!
