### ISSUE TITLE
[QUESTION] Export to Mp4?

### ISSUE THREAD

**Issue by rrzhang139** [NVIDIA/warp#340]
Are there options to export to mp4 and defining camera parameters like Blender? What is an alternative to this? Thanks!

**Comment by christophercrouzet** [comment]
Hi @rrzhang139, if you look at our examples, most of them export the result as a USD scene using `warp.render.UsdRenderer`. From there, you should be able to import it in Blender or any other 3D software and render it however you like.

An alternative could be to use `warp.render.OpenGLRenderer` instead and using its `get_pixels()` method to store each frame as an image. Then you could use `ffmpeg` to convert these as mp4, or maybe even use Matplotlib's `FuncAnimation` class.
