### ISSUE TITLE
[DOCS] Improve documentation for Warp arrays

### ISSUE THREAD

**Issue by mmacklin** [NVIDIA/warp#364]
## Category

- [ ] Report an error in the documentation.
- [x] Request for something to be documented.
- [ ] Request for a new [example](https://github.com/NVIDIA/warp/tree/main/warp/examples) to illustrate how to do something.
- [ ] Other (please explain)

## Description

Have an array attribute subsection similar to NumPy to list all the available attributes: https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes

Why this... warp arrays have .ndim and I can not find it in docs... just tried in the interactive Python interpreter.

(Filing on behalf of internal user.)

**Comment by shi-eric** [comment]
Closed because of f12a159425e005db85f08f3fd7a44da87b708da9
