### ISSUE TITLE
feature request: wp.bool type

### ISSUE THREAD

**Issue by jlinBE** [NVIDIA/warp#37]
currently the types available are:

scalar_types = [int8, uint8, int16, uint16, int32, uint32, int64, uint64, float32, float64]
vector_types = [vec2, vec3, vec4, mat22, mat33, mat44, quat, transform, spatial_vector, spatial_matrix]

there doesn't seem to be a bool type?

My specific use-case is to implement something like the activeIndices from Nvidia Flex that activates / deactivates particles on the GPU while still keeping them in memory.

**Comment by cadop** [comment]
I think it would be better to make this as a Discussion, since its not an issue

**Comment by shi-eric** [comment]
We have now added a wp.bool type in 36e1b14.
