### ISSUE TITLE
[BUG] Calling wp.atomic_add() does not update array arg write flag.

### ISSUE THREAD

**Issue by daedalus5** [NVIDIA/warp#378]
### Bug Description

Calling `wp.atomic_add()` from within a Warp kernel does not update the read/write flag of the array that is passed to this function. This means `wp.config.verify_autograd_array_access = True` does not detect array overwrites properly if this function is used.

**Comment by shi-eric** [comment]
This should be fixed by 089633b16442e7a0538f8106137a0d932881248b
