### ISSUE TITLE
Joints of URDF are not rendered

### ISSUE THREAD

**Issue by cadop** [NVIDIA/warp#40]
When running the examples and previewing in omniverse through the stored USD, it seemed like there were joints, but this was only by playing the simulation back.  However, there doesn't seem to be any joints

![image](https://user-images.githubusercontent.com/11399119/176303777-54b8870e-4d88-4ae0-b356-7e7c61b9c33a.png)

**Comment by cadop** [comment]
@yizhouzhao  That is USD

**Comment by mmacklin** [comment]
This is expected since we don't have a USD representation of joints, the output of the sim. is just time-sampled rigid body trajectories.

We will add support for the USD physics schema in the future that will allow this, but it won't be supported for URDF/MCJF sims.
