### ISSUE TITLE
Inconsistent behavior in example_dem.py

### ISSUE THREAD

**Issue by jlinBE** [NVIDIA/warp#43]
From example_dem.py:

    def update(self):
    
        with wp.ScopedTimer("simulate", active=True):
    
            if (self.use_graph):
    
                with wp.ScopedTimer("grid build", active=False):
                    self.grid.build(self.x, self.grid_cell_size)
    
                with wp.ScopedTimer("solve", active=False):
                    wp.capture_launch(self.graph)
                    wp.synchronize()
    
            else:
                for s in range(self.sim_substeps):
    
                    with wp.ScopedTimer("grid build", active=False):
                        self.grid.build(self.x, self.point_radius)
    
                    with wp.ScopedTimer("forces", active=False):
                        wp.launch(kernel=apply_forces, dim=len(self.x), inputs=[self.grid.id, self.x, self.v, self.f, self.point_radius, self.k_contact, self.k_damp, self.k_friction, self.k_mu], device=self.device)
                        wp.launch(kernel=integrate, dim=len(self.x), inputs=[self.x, self.v, self.f, (0.0, -9.8, 0.0), self.sim_dt, self.inv_mass], device=self.device)
                
                wp.synchronize()
			

The captured kernels are defined as:

    if (self.use_graph):
    
        wp.capture_begin()
    
        for s in range(self.sim_substeps):
    
            with wp.ScopedTimer("forces", active=False):
                wp.launch(kernel=apply_forces, dim=len(self.x), inputs=[self.grid.id, self.x, self.v, self.f, self.point_radius, self.k_contact, self.k_damp, self.k_friction, self.k_mu], device=self.device)
                wp.launch(kernel=integrate, dim=len(self.x), inputs=[self.x, self.v, self.f, (0.0, -9.8, 0.0), self.sim_dt, self.inv_mass], device=self.device)
            
        self.graph = wp.capture_end()
			

If use_graph==True, grid.build() is called once, then the kernels are replayed 64 times.  If use_graph==False, grid.build() is called every time the kernels are called.  I think this is a bug.

**Comment by mmacklin** [comment]
Thanks, fixed in 94da260d5cf0e3c7511d55d2c9df35cc5fd07b2d
