### ISSUE TITLE
Bug with `wp.pow`

### ISSUE THREAD

**Issue by epi-morphism** [NVIDIA/warp#46]
Seems to be a bug with `wp.pow` for negative values:
```python
@wp.kernel
def test(tt: wp.array(dtype=wp.float32)):
  tt[0] = wp.pow(-1., 2.)

tt = wp.zeros((1,), dtype=wp.float32, device='cuda')
wp.launch(test, dim=1, inputs=[tt], device='cuda')
print(tt)
```
The above prints `[nan]` while it should print `[-1]`. Could be an issue with my graphics card who knows but if not then it's probably a bug somewhere. (I'm getting the correct value with `device='cpu'`.)

**Comment by loliverhennigh** [comment]
I was seeing the same issue on a different example. For me it was random and about 50% of computations produced the nans. My work around was to just not use `pow` and do the multiplications out.

**Comment by mmacklin** [comment]
This is the default behavior for `powf()` on CUDA when using `--fast-math` (which is on by default) (https://forums.developer.nvidia.com/t/unsuspected-work-of-pow-function-pow-device-function-works-incorrectly-witn-negative-numbers/8089/2).

I agree though that this can be quite unexpected. I will revisit the use of `--fast-math`, we may actually add an option to turn this on/off per-module.

**Comment by mmacklin** [comment]
Just following up, we disabled `--fast-math` by default. You can now enable it on a per-module basis using `wp.set_module_options({"fast_math": True})`.

Best,
Miles
