### ISSUE TITLE
Colab support

### ISSUE THREAD

**Issue by epi-morphism** [NVIDIA/warp#47]
Just a heads up there seems to be some trouble getting warp running on colab. Installation itself can be patched through this
```
!export CUDA_HOME=/usr/local/cuda-11.1
!git clone https://github.com/NVIDIA/warp
%cd /content/warp
!python build_lib.py --cuda_path /usr/local/cuda-11.1
!pip install -e .
```
But there still seems to be an issue with running kernels that call an external function (`wp.func`), which I'm trying to track down.

**Comment by erwincoumans** [comment]
warp works fine in Google Colab now:

[!pip install warp-lang
import warp
warp.init()](url)
![Screenshot from 2023-11-17 20-24-15](https://github.com/NVIDIA/warp/assets/725468/c34aee1f-f813-4979-9d40-aea9cbe1846b)
