### ISSUE TITLE
Computing Jacobians

### ISSUE THREAD

**Issue by jotix16** [NVIDIA/warp#49]
What is the best way to compute the Jacobian  $\mathbf{J} \in \mathbb{R}^{m,n}$  of a function $\mathbf{f}(\mathbf x): \mathbb{R^n \to \mathbb{R}^m}$ in the Warp framework?

**Comment by half-potato** [comment]
Manually, with a custom kernel.

**Comment by mmacklin** [comment]
The Warp backwards pass computes `J^T*e` where `e` is a vector, by setting `e` to a one-hot array e.g.: `[1, 0, 0, 0...]` you can extract rows of the Jacobian, one per-backward pass.

If you have a number of environments you can also extract rows for each environment simultaneously by doing e.g.: `[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, ...]`, where each environment has e.g.: 4 DOFs.

We will add an example and some docs on this soon.

**Comment by mmacklin** [comment]
@eric-heiden for visibility.

**Comment by mmacklin** [comment]
Eric just added a nice example showing how to do this for single and multiple simulations / environments: 9c08291aa5a645f1e2ba38734c3fba85dad8d0cb.

Also see new section in the docs on this approach.

Cheers,
Miles
