### ISSUE TITLE
Are reductions possible? (e.g minimum/maximum)

### ISSUE THREAD

**Issue by oliver-batchelor** [NVIDIA/warp#57]
Hi there!

Thanks for making this library available - I am curious if there is a way to do reductions, for example I want to find the nearest point to a line (distance + index), for that some kind of reduction seems necessary.

Is this possible at the moment? I am presuming a for-loop is not the correct attempt, but from what I can tell the only reductions are additions or subtractions currently?

Thanks,
Oliver

**Comment by nishadgothoskar** [comment]
How did you compute minimum and maximum?
