### ISSUE TITLE
wp.svd3 not working

### ISSUE THREAD

**Issue by kasra-l1r** [NVIDIA/warp#63]
I am trying to use svd3, here is a small example

`import warp as wp

wp.init()

x = wp.diag(wp.vec3(1., 2., 3.))
u = wp.diag(wp.vec3(0., 0., 0.))
v = wp.diag(wp.vec3(0., 0., 0.))
s = wp.vec3(0., 0., 0.)

wp.svd3(x, u, s, v)`

I get this error message when running the code

`File "/home/kasra/Postdoc/projects/auto_design/code/alaki3.py", line 12, in <module>
    wp.svd3(x, u, s, v)
  File "/home/kasra/anaconda3/envs/auto_design/lib/python3.8/site-packages/warp/context.py", line 189, in __call__
    raise error
  File "/home/kasra/anaconda3/envs/auto_design/lib/python3.8/site-packages/warp/context.py", line 163, in __call__
    value_type = type_ctype(f.value_func(None))
  File "/home/kasra/anaconda3/envs/auto_design/lib/python3.8/site-packages/warp/context.py", line 155, in type_ctype
    elif issubclass(dtype, ctypes.Array):
TypeError: issubclass() arg 1 must be a class`

**Comment by mmacklin** [comment]
`wp.svd3()` is a kernel function that is really only designed to be called from within @wp.kernels - we do allow calling some built-in functions directly from the Python interpreter as a convenience (e.g.: simple vector operators), but it's not so simple for functions like this with multiple return values.

We may address this in the future, or at least give a better warning for methods where this is not supported. 

Closing as not planned for now.
