### ISSUE TITLE
just confirm: the default render using usd is not differentiable right?

### ISSUE THREAD

**Issue by zoezhou1999** [NVIDIA/warp#70]
Hi
Thank you for this awesome work!
just confirm: the default render using USD is not differentiable right?
if hope to use warp like gradSim, then need to replace the renderer with a differentiable renderer?
Thank you!

**Comment by daedalus5** [comment]
Thanks! 
That's right, the default USD renderer is not differentiable.
We have plans to add a simple differentiable raycaster soon :)

**Comment by mmacklin** [comment]
I will close this as we are not planning on supporting full differentiable USD rendering, but like Zach said we will add some pre-built example for how to write a differentiable ray-tracer with Warp.
