### ISSUE TITLE
Zero-copy conversion to CuPy array?

### ISSUE THREAD

**Issue by elibol** [NVIDIA/warp#71]
Is there a supported approach to converting a warp array to a cupy array, ideally without copying?

**Comment by mmacklin** [comment]
Hi @elibol, sorry for the late reply - Warp now supports the __cuda_array_interface__ protocol, so you can directly pass Warp arrays to CuPy, for example:

```import warp as wp
wp.init()

a = wp.zeros((10,), dtype=float)
a.fill_(1.0)

print(a)
# prints [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

import cupy as cp


b = cp.ones((10,), dtype=float)

# add a Warp array directly to a CuPy array
b = cp.add(b, a)

print(b)
# prints [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]

```
