### ISSUE TITLE
TypeError in warp.sim.model

### ISSUE THREAD

**Issue by Rabbit-Hu** [NVIDIA/warp#73]
Thank you for this cool library!

I noticed a small issue in the function `ModelBuilder.add_soft_mesh` in warp/sim/model.py, [line 1787 ](https://github.com/NVIDIA/warp/blob/d19058d5a39e7250b1459fba8dab20f640af0822/warp/sim/model.py#L1787):
```python
p = wp.quat_rotate(rot, v * scale) + pos
```
where pos is `List[float]`. Seems that addition between `wp.vec3` and `List[float]` is not supported and this line should be 
```python
p = np.array(wp.quat_rotate(rot, v * scale)) + pos
```
according to [other lines](https://github.com/NVIDIA/warp/blob/d19058d5a39e7250b1459fba8dab20f640af0822/warp/sim/model.py#L1560) in the same file. 

Thank you!

**Comment by eric-heiden** [comment]
Thanks for reporting the issue! It has been resolved recently.
