### ISSUE TITLE
urdfpy (and its depency networkx) has issues with Python 3.10 and numpy > 1.20

### ISSUE THREAD

**Issue by erwincoumans** [NVIDIA/warp#88]
See also https://github.com/mmatl/urdfpy/pull/23 and some 'fork'
This fork still has some issue using np.float (which has been removed, and should be replaced by float. Here is a newer fork that applies the fixes: https://github.com/erwincoumans/urdfpy and it can be installed (or put in a requirements.txt file) using:
`pip install git+https://github.com/erwincoumans/urdfpy`

**Comment by shi-eric** [comment]
The urdfpy dependency has been removed starting in `1.0.0-beta.1`.
