### ISSUE TITLE
Can't find warp in extensions list

### ISSUE THREAD

**Issue by mcfeely85** [NVIDIA/warp#9]
I'm not able to find warp in omniverse create/kit extensions list, do I need to turn on some settings?

thanks

![1](https://user-images.githubusercontent.com/8682933/159853541-1f9485d1-60dc-447a-a0f9-24dcd2478703.png)
![2](https://user-images.githubusercontent.com/8682933/159853549-29077e4c-c855-46fa-867a-1e6ccfa1acc7.png)

**Comment by cadop** [comment]
I think you need to download kit 103.  Or did you try adding the git repo to the extensions path?

**Comment by mmacklin** [comment]
Thanks @cadop, indeed, you need to use Create 103 (2022.1) released this week in the Launcher.
