### ISSUE TITLE
fileno

### ISSUE THREAD

**Issue by mingno** [NVIDIA/warp#90]
### in Maya

Error: AttributeError: file C:\Users\mingn\AppData\Roaming\Python\Python37\site-packages\warp\__init__.py line 9: 'maya.Output' object has no attribute 'fileno'

### in Blender

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\warp\__init__.py", line 9, in <module>
    faulthandler.enable()
io.UnsupportedOperation: fileno

**Comment by mmacklin** [comment]
Hmm, thanks @mingno - this could be due to the recent addition of the `faulthandler`. I will look to disable this or at least handle these exceptions.

Best,
Miles

**Comment by c0d1f1ed** [comment]
Thanks @mingno for reporting this! Could you give https://github.com/NVIDIA/warp/pull/92 a try?

**Comment by mmacklin** [comment]
We have disabled the `faulthandler` on init so I will close this for now.
