### ISSUE TITLE
Rigid-body contact issue/questions

### ISSUE THREAD

**Issue by zoezhou1999** [NVIDIA/warp#98]
Hi
I am playing https://github.com/NVIDIA/warp/blob/main/examples/example_sim_rigid_contact.py
When i set scale to 10 in this line, https://github.com/NVIDIA/warp/blob/643464030f78f4795857911a0263a984d1db2f99/examples/example_sim_rigid_contact.py#LL48C9-L48C19 , and set camera distance to 100. Also, comment out other objects except bunny.
I noticed that there is no collision between bunnies and floor. Bunnies are falling through the floor. Is it normal?
Thank you!

**Comment by eric-heiden** [comment]
Hi,

There indeed appears to be an issue in the contact handling that happens with the `SemiImplicitIntegrator`. We will release a fix for this soon, but in the meantime you could try the `XPBDIntegrator` by replacing [this line](https://github.com/NVIDIA/warp/blob/643464030f78f4795857911a0263a984d1db2f99/examples/example_sim_rigid_contact.py#L123) by:
```py
self.integrator = wp.sim.XPBDIntegrator()
```
XPBD generally yields more stable contact simulations without having to tune contact parameters like stiffness or damping.
